/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian
 */
public class EmployeeListForm extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeForm
     */
    private Connection conn;
    private PreparedStatement getData;
    public EmployeeListForm() {
        initComponents();
        db();
        SearchTFKeyReleased(null);
        
        
    }
    public void db(){
        try {
            String url = "jdbc:mysql://127.0.0.1:3306/sql_workbench?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT";
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(url, "root", "adrian024");
            String query = "SELECT * FROM employeedb WHERE " +
                           "employeeID LIKE ? OR " +
                           "firstName LIKE ? OR " +
                           "lastName LIKE ? OR " +
                           "bday LIKE ? OR " +
                           "dept LIKE ? OR " +
                           "position LIKE ? OR " +
                           "contact LIKE ?";
            getData = conn.prepareStatement(query);
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchTF = new javax.swing.JTextField();
        EmployeeListTitleLabel = new javax.swing.JLabel();
        SearchLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeListTable = new javax.swing.JTable();
        DataBaseNumRecordLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Information Record");
        setBounds(new java.awt.Rectangle(1280, 700, 1280, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchTF.setToolTipText("Enter data you want to search");
        SearchTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SearchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTFKeyReleased(evt);
            }
        });
        jPanel1.add(SearchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, 20));

        EmployeeListTitleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EmployeeListTitleLabel.setText("Employee Information Record");
        EmployeeListTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(EmployeeListTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        SearchLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        SearchLabel.setText("Search Record:");
        jPanel1.add(SearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        EmployeeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Full Name", "B-Day", "Department", "Position", "Contact #"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EmployeeListTable.setToolTipText("");
        EmployeeListTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        EmployeeListTable.setRequestFocusEnabled(false);
        EmployeeListTable.setShowGrid(true);
        jScrollPane1.setViewportView(EmployeeListTable);
        if (EmployeeListTable.getColumnModel().getColumnCount() > 0) {
            EmployeeListTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            EmployeeListTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            EmployeeListTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            EmployeeListTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            EmployeeListTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            EmployeeListTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 530, 280));

        DataBaseNumRecordLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DataBaseNumRecordLabel.setText("Total Record(s) in database are : ");
        DataBaseNumRecordLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        DataBaseNumRecordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(DataBaseNumRecordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTFKeyReleased
        // TODO add your handling code here:
              String searchText = SearchTF.getText();
        DefaultTableModel dtm = (DefaultTableModel) EmployeeListTable.getModel();
        int rowCount = EmployeeListTable.getRowCount();
        while (rowCount-- > 0) {
            dtm.removeRow(rowCount);
        }

        try {
            for (int i = 1; i <= 7; i++) {
                getData.setString(i, "%" + searchText + "%");
            }

            ResultSet rs = getData.executeQuery();
            while (rs.next()) {
                java.util.Vector v = new java.util.Vector();
                v.add(rs.getString("employeeID"));
                v.add(rs.getString("firstName") + " " + rs.getString("lastName"));
                v.add(rs.getString("bday"));
                v.add(rs.getString("dept"));
                v.add(rs.getString("position"));
                v.add(rs.getString("contact"));
                dtm.addRow(v);
            }

            Statement countStmt = conn.createStatement();
            ResultSet countRs = countStmt.executeQuery("SELECT COUNT(*) AS total FROM employeedb");
            if (countRs.next()) {
                int totalRows = countRs.getInt("total");
                DataBaseNumRecordLabel.setText("Total Record(s) in database are: " + totalRows);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage());
        }
    

    }//GEN-LAST:event_SearchTFKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataBaseNumRecordLabel;
    private javax.swing.JTable EmployeeListTable;
    private javax.swing.JLabel EmployeeListTitleLabel;
    private javax.swing.JLabel SearchLabel;
    private javax.swing.JTextField SearchTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
