/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;


import java.sql.*;
import java.awt.Image;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JCheckBox;
/**
 *
 * @author Adrian
 */
public class LoginForm extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst, pst1;
    ResultSet rs,rs1;
    String dbfirstName,dbfirstName1;
    String dbUserName;
    String dbPassword;
    String dbDecryptedPassword;
    String dbRole;
    String UserNameInput;
    String PasswordInput;
    String role1, role2;
    boolean isValidUserAdmin = false;
    boolean isValidUserUser = false;
    /**
     * Creates new form LoginForm
     */
    
    public LoginForm() {
        initComponents();
        LoginBackgroundMainLabel_scaleImg();
        CompanyLogoLabel_scaleImg();  
        Connect();
       
    }
    //Image scaling Method for LoginBackgroundMainLabel
    public void LoginBackgroundMainLabel_scaleImg() {
        ImageIcon icon = new ImageIcon("E:\\Source Code\\Java NC3\\OJT\\EmployeeManagementSystem\\src\\Resourses\\slider5.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(LoginBackgroundMainLabel.getWidth(), LoginBackgroundMainLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        LoginBackgroundMainLabel.setIcon(scaledIcon);    
    }
    //Image scaling Method for LoginBackgroundMainLabel
    public void CompanyLogoLabel_scaleImg() {
        ImageIcon icon = new ImageIcon("E:\\Source Code\\Java NC3\\OJT\\EmployeeManagementSystem\\src\\Resourses\\ARCENAL SYSTEMS_png.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(CompanyLogoLabel.getWidth(), CompanyLogoLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        CompanyLogoLabel.setIcon(scaledIcon);    
    }
    //db connection
    public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/sql_workbench","root","adrian024");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }
   
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        UserNameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        PasswordTF = new javax.swing.JPasswordField();
        ExitLabel = new javax.swing.JLabel();
        CompanyLogoLabel = new javax.swing.JLabel();
        chckbxShowPassword = new javax.swing.JCheckBox();
        BackgroundPanel = new javax.swing.JPanel();
        TaglineLabel2 = new javax.swing.JLabel();
        TaglineLabel1 = new javax.swing.JLabel();
        LoginBackgroundMainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        setFocusCycleRoot(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoginPanel.setDoubleBuffered(false);
        LoginPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNameTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UserNameTF.setToolTipText("Enter Username");
        UserNameTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTFActionPerformed(evt);
            }
        });
        LoginPanel.add(UserNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 23));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/user_circle_light_icon.png"))); // NOI18N
        jLabel1.setText("Username:");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 20));

        PasswordLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/key_icon.png"))); // NOI18N
        PasswordLabel.setText("Password:");
        PasswordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PasswordLabel.setVerifyInputWhenFocusTarget(false);
        LoginPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, 90, -1));

        LoginBtn.setBackground(new java.awt.Color(0, 204, 255));
        LoginBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/white_enter_icon.png"))); // NOI18N
        LoginBtn.setText("Log in");
        LoginBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        LoginPanel.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 40));

        PasswordTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PasswordTF.setToolTipText("Enter Password");
        PasswordTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTFActionPerformed(evt);
            }
        });
        LoginPanel.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 22));

        ExitLabel.setBackground(new java.awt.Color(255, 255, 255));
        ExitLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ExitLabel.setForeground(new java.awt.Color(255, 0, 0));
        ExitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLabel.setText("X");
        ExitLabel.setToolTipText("");
        ExitLabel.setAutoscrolls(true);
        ExitLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 0, 0), java.awt.Color.black, new java.awt.Color(255, 0, 0)));
        ExitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ExitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLabelMouseClicked(evt);
            }
        });
        LoginPanel.add(ExitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 1, 21, -1));

        CompanyLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompanyLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/ARCENAL SYSTEMS_png.png"))); // NOI18N
        CompanyLogoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CompanyLogoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginPanel.add(CompanyLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 80));

        chckbxShowPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chckbxShowPassword.setText("Show Password");
        chckbxShowPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chckbxShowPasswordItemStateChanged(evt);
            }
        });
        LoginPanel.add(chckbxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 200, -1));

        BackgroundPanel.setBackground(new java.awt.Color(51, 204, 255));
        BackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        BackgroundPanel.setRequestFocusEnabled(false);
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TaglineLabel2.setBackground(new java.awt.Color(255, 255, 255));
        TaglineLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        TaglineLabel2.setForeground(new java.awt.Color(255, 255, 255));
        TaglineLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaglineLabel2.setText("Making things happen");
        TaglineLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackgroundPanel.add(TaglineLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, 30));

        TaglineLabel1.setBackground(new java.awt.Color(255, 255, 255));
        TaglineLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        TaglineLabel1.setForeground(new java.awt.Color(255, 255, 255));
        TaglineLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaglineLabel1.setText("Creating your visions,");
        TaglineLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackgroundPanel.add(TaglineLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, -1));

        LoginBackgroundMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginBackgroundMainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/slider5.jpg"))); // NOI18N
        LoginBackgroundMainLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackgroundPanel.add(LoginBackgroundMainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_ExitLabelMouseClicked

    private void PasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTFActionPerformed

    private void UserNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTFActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        UserNameInput = UserNameTF.getText();
        PasswordInput = new String(PasswordTF.getPassword());
        role1 = "admin";
        role2 = "user";       
        UserNameTF.setText("");
        PasswordTF.setText("");
        try {
            pst = con.prepareStatement("select * from userdb");
            pst1 = con.prepareStatement("select userName, password, aes_decrypt(password,'key123') as decrypted_password, role from userdb");
            rs = pst.executeQuery();
            rs1 = pst1.executeQuery();

            while (rs.next() && rs1.next()) {
                dbUserName = rs1.getString("userName");
                dbPassword = rs.getString("password");
                dbDecryptedPassword = rs1.getString("decrypted_password");
                dbRole = rs1.getString("role");

            if (UserNameInput.equals(dbUserName) && (PasswordInput.equals(dbPassword) || PasswordInput.equals(dbDecryptedPassword))) {
                if (dbRole.equals(role1)) {
                    isValidUserAdmin = true;
                    dbfirstName = rs.getString("firstName");                                       
                } else if (dbRole.equals(role2)) {
                    isValidUserUser = true;
                    dbfirstName1 = rs.getString("firstName");                      
                }
            }
        }
            
        if (isValidUserAdmin || isValidUserUser) {
            JOptionPane.showMessageDialog(this, "Login successful!");
            this.setVisible(false);           
        } else {
            JOptionPane.showMessageDialog(this, "Enter a valid Username/Password!");
        }
        if (isValidUserAdmin) {
            MainForm main = new MainForm();
            main.NameLabel.setText("NAME: " + dbfirstName); 
            main.userType=role1;
            main.setVisible(true);
        } else if (isValidUserUser) {
            MainForm main = new MainForm();
            main.userType=role2;
            main.NameLabel.setText("NAME: " + dbfirstName1);
            main.setVisible(true);
        }

        
    } catch (SQLException ex) {
        ex.printStackTrace(); // Print the stack trace for better error handling
    }
       
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void chckbxShowPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chckbxShowPasswordItemStateChanged
     // check box to show password
        JCheckBox showPassword = (JCheckBox)evt.getSource();
       if (showPassword.isSelected()) PasswordTF.setEchoChar((char)0);
        else PasswordTF.setEchoChar('\u25cf');
    }//GEN-LAST:event_chckbxShowPasswordItemStateChanged
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel CompanyLogoLabel;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JLabel LoginBackgroundMainLabel;
    public javax.swing.JButton LoginBtn;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel PasswordLabel;
    public javax.swing.JPasswordField PasswordTF;
    private javax.swing.JLabel TaglineLabel1;
    private javax.swing.JLabel TaglineLabel2;
    public javax.swing.JTextField UserNameTF;
    private javax.swing.JCheckBox chckbxShowPassword;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
