/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian
 */
public class SplashForm extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public SplashForm() {
        initComponents();
        BackGroundLabel_scaleImg();  //Image scaling for Background Label
        CompanyLogoLabel_scaleImg(); //Image scaling for Company logo Label
    }
    //Image scaling Method for Background Label
    public void  BackGroundLabel_scaleImg() {
    ImageIcon icon = new ImageIcon("E:\\Source Code\\Java NC3\\OJT\\EmployeeManagementSystem\\src\\Resourses\\slider1.jpg");
    Image img = icon.getImage();
    Image imgScale = img.getScaledInstance(BackGroundLabel.getWidth(), BackGroundLabel.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    BackGroundLabel.setIcon(scaledIcon);
}
    //Image scaling Method for Company logo Label
    public void  CompanyLogoLabel_scaleImg() {
    ImageIcon icon = new ImageIcon("E:\\Source Code\\Java NC3\\OJT\\EmployeeManagementSystem\\src\\Resourses\\ARCENAL SYSTEMS_png.png");
    Image img = icon.getImage();
    Image imgScale = img.getScaledInstance(CompanyLogoLabel.getWidth(), CompanyLogoLabel.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    CompanyLogoLabel.setIcon(scaledIcon);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ProgressBar = new javax.swing.JProgressBar();
        PercentLbl = new javax.swing.JLabel();
        LoadingLbl = new javax.swing.JLabel();
        CompanyLogoLabel = new javax.swing.JLabel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        MainPanel.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 716, 1020, 24));

        PercentLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PercentLbl.setForeground(new java.awt.Color(255, 255, 255));
        PercentLbl.setText("0%");
        MainPanel.add(PercentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 680, -1, -1));

        LoadingLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LoadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        LoadingLbl.setText("Loading...");
        MainPanel.add(LoadingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        CompanyLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/ARCENAL SYSTEMS_png.png"))); // NOI18N
        CompanyLogoLabel.setText("jLabel1");
        MainPanel.add(CompanyLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 890, 220));

        BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resourses/slider1.jpg"))); // NOI18N
        BackGroundLabel.setText("jLabel2");
        MainPanel.add(BackGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 716));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /*SplashForm sp = new SplashForm();
        sp.setVisible(true);
        try {
            for(int i=0;i<=100;i++){
                Thread.sleep(60);
                sp.PercentLbl.setText(i+"%");
                
                if(i==10)sp.LoadingLbl.setText("Turning on Modules...");
                if(i==20)sp.LoadingLbl.setText("Loading Modules...");
                if(i==50)sp.LoadingLbl.setText("Connecting to Database...");
                if(i==70)sp.LoadingLbl.setText("Connection Successful...");
                if(i==80)sp.LoadingLbl.setText("Launching Application...");
                sp.ProgressBar.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           sp.setVisible(false);  
           new LoginForm().setVisible(true);
           */
        
        
        
        
        

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashForm().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JLabel CompanyLogoLabel;
    public javax.swing.JLabel LoadingLbl;
    private javax.swing.JPanel MainPanel;
    public javax.swing.JLabel PercentLbl;
    public javax.swing.JProgressBar ProgressBar;
    // End of variables declaration//GEN-END:variables
}
